version: '3.8'
services:
    php:
        build:
            context: ./docker
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/app
            - ~/.composer:/var/www/.composerhost
            - ~/.ssh:/var/www/.ssh
