on:
    - push
name: CI
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: php-actions/composer@v6
            -   name: Psalm
                run: composer psalm
            -   name: CodeSniffer
                run: composer phpcs
            -   name: PHPUnit
                run: composer phpunit-ci
